= WikiLink Application - Neo4j & Wikipedia graph visualization

WikiLink is a web application for interactive graph exploration of Wikipedia categories and pages, using Neo4j as the database and Flask + d3.js/Popoto.js on the frontend. This project was built as a personal exploration of knowledge graphs and visual interfaces for navigating Wikipedia’s category system.

Originally built in 2017 and republished in 2026 as a clean v1.0 snapshot of the same code.

== Quick start

. Create and activate a virtualenv (optional but recommended).
. Install Python dependencies with `pip install -r requirements.txt` (and `flask-autodoc` if needed).
. Install Neo4j locally with the APOC plugin and make sure it runs on `localhost:7474`.
. Configure Neo4j credentials in the PowerShell scripts and in `wikilink.py` / `wikilink-popoto.search.js`.
. Load the dataset using the `wikilink_create_categories.bat` and `wikilink_process_data*.bat` scripts.
. Start the Flask app with `python wikilink.py` and open `http://localhost:8080`.

== Stack

* https://github.com/neo4j-examples/movies-python-bolt - Example app used as base
* https://github.com/versae/neo4j-rest-client[neo4jrestclient] - Neo4j Python driver
* http://flask.pocoo.org/[Flask] - Python microframework based on Werkzeug, Jinja2 and good intentions
* Neo4j-Server
* Frontend: jQuery, Bootstrap, http://d3js.org/[d3.js], Popoto.js

== Setup

First get yourself set up with http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtualenv] so we don’t break any other Python stuff you have on your machine. You can go to the next step (install dependencies for the app) if you want to bypass creating a virtualenv. We use Python 3+. After you’ve got that installed, let’s set up an environment for our app:

[source,bash]
----
$ virtualenv wikilink
$ source wikilink/bin/activate
----

The next step is to install the dependencies for the app:

[source,bash]
----
(wikilink)$ pip install -r requirements.txt
# Maybe this is also needed:
(wikilink)$ pip install flask-autodoc
----

== Run locally

Ensure you have Neo4j DB installed as localhost. If it is not already installed, get OpenJDK 8 or Oracle Java 8, recommended for Neo4j 3.0.x. Version 7 is recommended for releases prior to 2.3.0.

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), and open the http://localhost:7474/[Neo4j Browser].

Ensure you have the APOC plugin installed. If you use Neo4j Desktop go to `Manage > Plugins > APOC > Install` and restart your DB. Otherwise, download the `.jar` package from the Neo4j website and place it in the `/neo4j/plugins` folder.

It is possible you have APOC use restricted by security settings in Cypher. Un-restrict it by adding the following line to the `conf/neo4j.conf` file:

[source]
----
dbms.security.procedures.unrestricted=apoc.*
----

If your Neo4j services start is not automatic, you can start them through `wikilink/neo4j_run.bat` execution, assuming you have Neo4j installed on path `C:\Neo4j`.

You will need to edit `wikilink/neo4j/wikilink_create_categories.ps1` and `wikilink/neo4j/wikilink_process_data.ps1` files to set your own Neo4j user/password.

Then install the dataset running `wikilink/neo4j/wikilink_create_categories.bat`. You can edit it to add commented categories creation with `//`. Then prepare all the data running `wikilink/neo4j/wikilink_process_data.bat` to load a single category in 1–5 minutes or `wikilink/neo4j/wikilink_process_data_all.bat` to process all the dataset.

Finally, configure Python authentication with Neo4j and the contact form:

On the Neo4jRestClient folder in your Python installation, open the client config `.py` file and set up user & password. On `wikilink/wikilink.py` replace the placeholders with your Neo4j DB authentication.

[source,python]
----
password = ""
driver = neoGDB.driver("bolt://localhost", auth=basic_auth("", password))
----

In `wikilink/static/js` you will need to modify `wikilink-popoto.search.js` file, adding the Neo4j password on this line:

[source,javascript]
----
popoto.rest.AUTHORIZATION = "Basic " + btoa();
----

For the contact form, in the same `wikilink/wikilink.py` file replace the settings below with your email settings. Default ones work with a Gmail account.

[source,python]
----
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 465
app.config['MAIL_USE_SSL'] = True
app.config['MAIL_USERNAME'] = 'YourUser@NameHere'
app.config['MAIL_PASSWORD'] = 'yourMailPassword'
----

And finally let’s start up a Flask web server. You can do it by clicking directly `wikilink/wikilink_run.bat` file, or executing the command below:

[source,bash]
----
(wikilink)$ python wikilink.py
 * Running on http://127.0.0.1:8080/
----

Navigate to http://localhost:8080 and you should see your WikiLink application.

== Future ideas

Even though this project is considered feature-complete and I don’t plan to actively maintain it, there are some ideas that could be explored in the future:

- Replace `neo4jrestclient` with the official Neo4j Python driver.
- Add Docker Compose setup for Neo4j + Flask to simplify local setup.
- Explore migrating the frontend to a modern JS framework while keeping Popoto.js for graph exploration.

