== WikiLink Application - Neo4j & Wikipedia graph visualization

=== Stack

* https://github.com/neo4j-examples/movies-python-bolt - Example app used as base
* https://github.com/versae/neo4j-rest-client[neo4jrestclient] - Neo4j Python driver
* http://flask.pocoo.org/[Flask] - Python microframework based on Werkzeug, Jinja 2 and good intentions.
* Neo4j-Server
* Frontend: jquery, bootstrap, http://d3js.org/[d3.js], pototo.js


=== Setup

First get yourself setup with link:http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtualenv] so we don't break any other Python stuff you have on your machine. 
You can go to next step - install dependencies for the app - if you want to bypass to create a virtualenv.
We use Python 3+ version.
After you've got that installed let's setup an environment for our app:

[source]
----
$ virtualenv wikilink
$ source wikilink/bin/activate
----

The next step is to install the dependencies for the app:

[source]
----
(wikilink)$ pip install -r requirements.txt

Maybe is also needed this.
(wikilink)$ pip install flask-autodoc

----

=== Run locally

Ensure you have Neo4j DB as localhost installed.
If it is not already installed, get OpenJDK 8 or Oracle Java 8, recommended for Neo4j 3.0.x. Version 7 is recommended for releases prior to 2.3.0.

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser]. 

Ensure you have the apoc plugin installed. For it, if you use Neo4j Desktop go to > Manage > Plugins > APOC > Install and restart your DB. 
Otherwise, download the .jar package from Neo4j web and place it on /neo4j/plugins folder.

It is possible you have restricted by security cypher apoc use.
Un-restrict it added following line to <neo4j folder>\conf\neo4j.conf file.
[source]
----
dbms.security.procedures.unrestricted=apoc.*
----

If your Neo4j services start is not automatic, you can start them through \wikilink\neo4j_run.bat execution, assuming you have Neo4j installed on path C:\Neo4j.

You will need to edit /wikilink/neo4j/wikilink_create_categories.ps1 & /wikilink/neo4j/wikilink_process_data.ps1 files to set your own Neo4j user/password.

Then install the data-set run /wikilink/neo4j/wikilink_create_categories.bat . You can edit it to add commented categories creation with "//".
Then prepare all the data running /wikilink/neo4j/wikilink_process_data.bat to load a single category in 1-5 minutes or /wikilink/neo4j/wikilink_process_data_all.bat to process all the dataset. 

For last, let's check python authentication with Neo4j & the contact form:

On Neo4jRestClient folder on your python folder, open the client conf .py file and set up user & password.
On wikilink\wikilink.py replace <neo4j_user> & <neo4j_password> with your Neo4j db authentication.

[source]
----
password = "<neo4j_password>" 
driver = neoGDB.driver('bolt://localhost',auth=basic_auth("<neo4j_user>", password))
----

On wikilink\static\js you will need to modify wikilink-popoto.search.js file, adding Neo4j password on this line:

[source]
----
popoto.rest.AUTHORIZATION = "Basic " + btoa(<Neo4j-password>);
----

For the contact form, on same wikilink/wikilink.py file replace below settings with your email settings. Default ones work with a Gmail account.

[source]
----
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 465
app.config['MAIL_USE_SSL'] = True
app.config['MAIL_USERNAME'] = 'YourUser@NameHere'
app.config['MAIL_PASSWORD'] = 'yourMailPassword'
----

And finally let's start up a Flask web server. You can do it cliking directly wikilink\wikilink_run.bat file, or executing command below

[source]
----
(wikilink)$ python wikilink.py
 * Running on http://127.0.0.1:8080/
----

Navigate to http://localhost:8080 and you should see your WikiLink application
